### ISSUE TITLE
docker配置后了启动不了

### ISSUE THREAD

**Issue by wujita01** [F1renze/flask_movie_3#2]
Can't connect to MySQL server on '127.0.0.1' (115)，一直显示这个错误。这是配置文件。`set APP_WEBC=production
@rem # 指定 App 使用何种配置
set APP_MH=127.0.0.1
@rem # App 使用的 Mysql Host, 此为 docker-compose service name
set APP_MDB=cili_db
@rem # App 使用的 DB, 与 SQL File 同步
@rem DB Container default user root, pwd secret
set APP_MU=root
@rem # App 使用的 Mysql 用户
set APP_MP=123456
@rem # App 使用的 Mysql 用户的密码
set APP_RH=default
@rem # App 使用的 Redis Host, 此为 docker-compose service name
@rem Recommended to use SendGrid
set APP_MAILS=YouLink
@rem # 指定 Flask-Mail 邮件服务器
set APP_MAILU=YouLike
@rem # 邮件服务器登录用户
set APP_MAILP=YouLike
@rem # 邮件服务器登录密码
set APP_SENDER=YouLike
@rem # App 发送邮件的发件人
docker-compose -f ./zbuild/docker-compose.yml up -d --build`

**Comment by wujita01** [comment]
搭建成功了。回来留个爪。windows系统不要捣鼓。centos 7搞定了。

**Comment by e1ijah1** [comment]
Sorry, 现在才看到 Issue, 不过还是恭喜你搭建成功呢
